version: "3.9"

services:

  backend:
    build: .
    container_name: sales-backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: sales-frontend
    ports:
      - "8502:8502"
    depends_on:
      - backend
    restart: always